### ISSUE TITLE
Add a translation for "Outil de Recherche de Compromission" in introduction

### ISSUE THREAD

**Issue by rgayon** [DFIR-ORC/dfir-orc.github.io#1]

**Comment by jgautier-anssi** [comment]
Hi rgayon,

Thank you so much for your issue.

[Let me Bing that for you!](https://fr.lmgtfy.com/?q=bing%20translate%20swiss%20outil%20de%20recherche%20de%20compromission&s=b) ¯\_(ツ)_/¯

Jean

**Comment by rgayon** [comment]
My apologies for not being more clear initially, it was never my intent to ask for an official translation of "outil de recherche de compromission".

As the French speaker on-call in the office, I had a couple people reporting to me it would be nice to have  an English translation of "Outil de Recherche de Compromission" on the dfir-orc.github.io page, so they wouldn't have to use automated, or organic, translation services.
Would you consider re-opening this issue, or should I file another one?

On a side note, is very disappointing to see Bing considering "Swiss" to be a language, that is equal to "German".

**Comment by md-anssi** [comment]
Hi Romain,
We should not have answered this way and it won't happen again, we apologize. This was treated as a joke and on kind of a personal level, whereas this is not the place for it.
The website is being extended with a tutorial and a lot of information about the embedded tools.
We plan on releasing it as soon as we can, next week or the week after that.
When releasing the new version, we will translate the tool name.
I think Outil de Recherche de Compromission can be translated as "tool to search for compromised machines", or something like that. As most acronyms, it does not translate that well... 
Cheers,
The DFIR ORC team

**Comment by rgayon** [comment]
Thank you for your kind reply, no need to apologize for anything, I'm certain everyone here has had good intent!
I wish English had a good word for "compromission" too =) Something like "Indicator of compromise Research Tool" maybe?
